default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  port: <%= Rails.application.credentials.dig(:database, :port) %>
  host: <%= Rails.application.credentials.dig(:database, :host) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: housemate_development
test:
  <<: *default
  database: housemate_test